name = "ClusterPermutationTests"
uuid = "e3bc594e-7e39-4b61-be5a-4b8b3e7ff14e"
version = "0.4.0-dev"
authors = ["Oliver Lindemann"]

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
CPTestMakieExt = ["Makie"]

[compat]
Aqua = "0.8"
CSV = "0.10"
CategoricalArrays = "0.10, 1"
DataAPI = "1.16.0"
Downloads = "1.6"
GLM = "1.9.0"
HypothesisTests = "0.11"
Logging = "1"
Makie = "0.23, 0.24"
MixedModels = "5.1.0"
MixedModelsDatasets = "0.1.2"
ProgressMeter = "1"
Random = "1"
Reexport = "1"
StatsAPI = "1"
StatsBase = "0.34.6"
StatsModels = "0.7"
Tables = "1.12.1"
Test = "1"
TypedTables = "1.4.6"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
MixedModelsDatasets = "7e9fb7ac-9f67-43bf-b2c8-96ba0796cbb6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "MixedModelsDatasets", "CSV", "Downloads"]
